project:
  type: website

website:
  title: "Evan's Blog"
  description: "A blog about quantum computing, programming, and other things."
  favicon: assets/favicon.ico
  site-url: https://blog.evm9.dev
  navbar:
    right:
      - icon: github
        href: https://github.com/evmckinney9/jenglot
format:
  html:
    theme: default  
    css: assets/css/styles.css

resources:
  - CNAME

